name: dotnet
base: core22
adopt-info: dotnet-installer
summary: .NET CLI tools, SDK, and Runtime
description: |
  .NET is the free, open-source, cross-platform framework for building modern
  apps and powerful cloud services that work on Android, iOS, GNU/Linux, macOS
  and Windows.
  .
  This Snap also includes a powerful installer tool that allows you to manage
  your .NET installation and gives you the possibility to install as many
  multiple versions of .NET side-by-side as you want, as well as receive
  monthly security and feature updates whenever they become available.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

package-repositories:
  - type: apt
    ppa: dotnet/snaps
    priority: always

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

parts:
  dotnet-installer:
    plugin: dump
    source: .
    build-packages:
      - dotnet-sdk-9.0
      - patchelf
    stage-packages:
      - jq
      - libicu70
    build-attributes:
      - enable-patchelf
    override-build: |
      /usr/bin/dotnet --info
      SNAP_VERSION=$(/usr/bin/dotnet --list-runtimes | grep NETCore.App | awk '{print $2}' | sort -r | head -n 1)
      craftctl set version="$SNAP_VERSION"

      if [ "${CRAFT_ARCH_BUILD_FOR}" = "amd64" ]; then
        RUNTIME_RID="linux-x64"
      elif [ "${CRAFT_ARCH_BUILD_FOR}" = "arm64" ]; then
        RUNTIME_RID="linux-arm64"
      else
        echo "Unsupported architecture (${CRAFT_ARCH_BUILD_FOR})"
        exit 1
      fi

      /usr/bin/dotnet publish src/Dotnet.Installer.Console --output "${SNAPCRAFT_PART_INSTALL}" \
        --configuration Release -r "${RUNTIME_RID}" -p:DebugSymbols=false -p:DebugType=none
      chmod 555 "${SNAPCRAFT_PART_INSTALL}/Dotnet.Installer.Console"

      patchelf --force-rpath --set-rpath \
        \$ORIGIN/netcoredeps:\$ORIGIN/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/core22/current/lib/{CRAFT_ARCH_TRIPLET_BUILD_FOR} \
        ${SNAPCRAFT_PART_INSTALL}/Dotnet.Installer.Console

  dotnet-host:
    plugin: nil
    build-packages:
      - patchelf
    stage-packages:
      - dotnet-hostfxr-9.0
    override-build: |
      DOTNET_VERSION=$(craftctl get version)
      INTERPRETER=$(find /usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR} -type f -name ld-linux** | head -n 1)
      patchelf --set-interpreter ${INTERPRETER} ${SNAPCRAFT_PART_INSTALL}/usr/lib/dotnet/dotnet
      patchelf --force-rpath --set-rpath \
        /snap/dotnet/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/core22/current/lib/{CRAFT_ARCH_TRIPLET_BUILD_FOR} \
        ${SNAPCRAFT_PART_INSTALL}/usr/lib/dotnet/dotnet
      patchelf --force-rpath --set-rpath \
        /snap/dotnet/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/core22/current/lib/{CRAFT_ARCH_TRIPLET_BUILD_FOR} \
        ${SNAPCRAFT_PART_INSTALL}/usr/lib/dotnet/host/fxr/${DOTNET_VERSION}/libhostfxr.so

  netstandard-targeting-pack:
    plugin: nil
    stage-packages:
      - netstandard-targeting-pack-2.1-9.0

apps:
  dotnet:
    command: Scripts/dotnet-launcher.sh
    environment:
      DOTNET_INSTALL_DIR: $SNAP_COMMON/dotnet

  dotnet-installer:
    command: Scripts/dotnet-installer-launcher.sh
    environment:
      DOTNET_INSTALL_DIR: $SNAP_COMMON/dotnet
