name: dotnet
base: core22
version: 8.0.1
summary: .NET CLI tools, SDK and runtime
description: |
  .NET is the free, open-source, cross-platform framework for building modern
  apps and powerful cloud services that work on Android, iOS, GNU/Linux, macOS
  and Windows.
  .
  This Snap also includes a powerful installer tool that allows you to manage
  your .NET installation and gives you the possibility to install as many
  multiple versions of .NET side-by-side as you want, as well as receive
  monthly security and feature updates whenever they become available.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

package-repositories:
  - type: apt
    ppa: dotnet/dotnet8

parts:
  dotnet-installer:
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: .
    build-packages:
      - dotnet-sdk-8.0
    build-attributes:
      - enable-patchelf
    stage-packages:
      - liblttng-ust1
      - libicu70
      - libssl3
    prime:
      - Dotnet.Installer.Console
      - Configuration/*
      - Scripts/*
      - usr/*

  dotnet-host:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - dotnet-hostfxr-8.0
  
  netstandard-targeting-pack:
    plugin: nil
    stage-packages:
      - netstandard-targeting-pack-2.1-8.0

apps:
  dotnet:
    command: Scripts/dotnet-initiator.sh
    environment:
      DOTNET_ROOT: $SNAP_COMMON/dotnet
      DOTNET_INSTALL_DIR: $SNAP_COMMON/dotnet
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu
      SERVER_URL: https://raw.githubusercontent.com/mateusrodrigues/pages-test/main/
