#!/usr/bin/env bash

set -euxo pipefail

# Create $SNAP_COMMON if doesn't exist
mkdir --parents "$SNAP_COMMON"

# Create .NET installation directory
mkdir --parents "$SNAP_COMMON"/dotnet
# Create snap configuration directory
mkdir --parents "$SNAP_COMMON"/snap

# Create an empty local manifest file if it doesn't yet exist.
if [ ! -e "$SNAP_COMMON"/snap/manifest.json ]; then
    echo "[ ]" > "$SNAP_COMMON"/snap/manifest.json
fi

# Install .NET SDK
DOTNET_INSTALL_DIR=$SNAP_COMMON/dotnet "$SNAP"/Dotnet.Installer.Console install sdk lts
