#!/bin/sh -e

# Create $SNAP_COMMON if doesn't exist
if [ ! -d "$SNAP_COMMON" ]; then
    mkdir -p "$SNAP_COMMON"
fi

# Create .NET installation directory
mkdir "$SNAP_COMMON"/dotnet
# Create snap configuration directory
mkdir "$SNAP_COMMON"/snap

# Create an empty local manifest file if it doesn't yet exist.
if [ ! -e "$SNAP_COMMON"/snap/manifest.json ]; then
    echo "[ ]" > "$SNAP_COMMON"/snap/manifest.json
fi
