#!/usr/bin/env bash

set -euxo pipefail

########################################################
# Remove remaining systemd-mount units from the system #
########################################################

find /usr/lib/systemd/system/ -type f -name 'var-snap-dotnet-common-dotnet-*.mount' | while read -r file; do
    unit_name=$(echo "$file" | rev | cut -d / -f 1 | rev)
    systemctl stop "$unit_name"
    systemctl disable "$unit_name"
    rm "$file"
done

#######################################################
# Remove remaining systemd-path units from the system #
#######################################################

find /usr/lib/systemd/system/ -type f -name 'dotnet-*-update-watcher.*' | while read -r file; do
    unit_name=$(echo "$file" | rev | cut -d / -f 1 | rev)
    systemctl stop "$unit_name"
    systemctl disable "$unit_name"
    rm "$file"
done

find /usr/lib/systemd/system/ -type f -name 'aspnetcore-*-update-watcher.*' | while read -r file; do
    unit_name=$(echo "$file" | rev | cut -d / -f 1 | rev)
    systemctl stop "$unit_name"
    systemctl disable "$unit_name"
    rm "$file"
done

systemctl daemon-reload
